backend:
  name: github
  repo: enlightenedu/github.io
  branch: main
  base_url: https://enlightenedu.github.io/github.io/admin/oauth/index.html#

media_folder: "images/uploads"
public_folder: "/github.io/images/uploads"

site_url: https://enlightenedu.github.io/github.io
display_url: https://enlightenedu.github.io/github.io

locale: "zh_Hans"

collections:
  - name: "news"
    label: "News"
    label_singular: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{date}}"
    sortable_fields: ["date", "title"]
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Category", name: "category", widget: "select", options: [{ label: "Company News", value: "Company News" }, { label: "Industry Insights", value: "Industry Insights" }, { label: "Case Study", value: "Case Study" }, { label: "Events", value: "Events" }], default: "Company News" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
